### ISSUE TITLE
Windows Builds

### ISSUE THREAD

**Issue by jared-w** [haskell-works/cabal-cache#129]
Does cabal-cache work on windows? If so, how much extra effort would be required in order to get windows working in CI so that upstream usages in CI could benefit from being able to seamlessly swap this in for preexisting caching strategies? I'm currently interested in figuring out how to set this up inside the `actions/setup-haskell` action, but the lack of Windows binaries is a blocker at the moment.

**Comment by newhoggy** [comment]
I'm very much interested in getting this to work on Windows.

The main blocker is that `cabal-cache` currently invokes the external program `tar` because the Haskell `tar` library doesn't understand `tar` files that have filenames longer than a certain limit.

Are you able to in your build environment ensure that `tar` is always available?

**Comment by newhoggy** [comment]
I've started a branch for supporting Windows:

https://github.com/haskell-works/cabal-cache/pull/130

**Comment by jared-w** [comment]
For github actions, specifically, the `tar` executable is indeed [always available](https://github.com/actions/toolkit/blob/main/packages/cache/src/internal/tar.ts). In general, this is not possible, but then again neither is the existence of *any* external binary, if I'm being pedantic...

I think that would be enough to get it at least working on most typical windows CI systems (which would probably be its main usecase)

**Comment by newhoggy** [comment]
I was wondering that since you're going to use the this from Github Actions and this project is currently missing CI builds for Windows if you'd be able to contribute Github Action support to the project to help with its ongoing maintenance on that platform.

**Comment by jared-w** [comment]
I can do that. I'll be back in the office in a few days and should be able to get something written shortly after, hopefully
