### ISSUE TITLE
Trying to use root of the S3 bucket results in `/` key.

### ISSUE THREAD

**Issue by Fuuzetsu** [haskell-works/cabal-cache#152]
If we set the bucket url to something like `s3://foo`, cabal-cache will upload objects to `s3://foo//v2/…`. Note the extra slash.

It's ugly and confusing and means we have to specify some prefix for no reason if the bucket is dedicated to the cabal cache.

**Comment by newhoggy** [comment]
Can you check if the following PR fixes this for you?

https://github.com/haskell-works/cabal-cache/pull/157
