### ISSUE TITLE
support multicloud

### ISSUE THREAD

**Issue by romanov-dv** [haskell-works/cabal-cache#162]
Hi! Can I use specific S3 endpoint? I did not find a suitable option

**Comment by mgajda** [comment]
It would require changing the Amazonka S3 configuration:
https://hackage.haskell.org/package/amazonka-core-1.6.1/docs/Network-AWS-Types.html#t:Service
Probably substitutiing this function after `Service` record was created [_svcEndpoint]() :: !([Region](https://hackage.haskell.org/package/amazonka-core-1.6.1/docs/Network-AWS-Types.html#t:Region) -> [Endpoint](https://hackage.haskell.org/package/amazonka-core-1.6.1/docs/Network-AWS-Types.html#t:Endpoint)).

Allowing custom endpoint function would allow to support multicloud - [numerous](https://www.backblaze.com/b2/docs/s3_compatible_api.html) [services](https://www.scaleway.com/en/object-storage/) [that](https://upcloud.com/community/tutorials/object-storage/) [support](https://www.linode.com/products/object-storage/) [S3 protocol](https://rclone.org/s3/), but have non-standard endpoints.

**Comment by mgajda** [comment]
@romanov-dv Can you please rename this ticket to "support multicloud"?

**Comment by hasufell** [comment]
Fix here: https://github.com/haskell-works/cabal-cache/pull/163
