### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by newhoggy** [haskell-works/cabal-cache#211]
@hasufell Would you be interested in collaborating in Slack?

We're currently collaborating strictly via Github tickets and PRs, but it's not straightforward for me to send a message to you directly.

**Comment by newhoggy** [comment]
The local functional programming meetup in Sydney called FPSyd as a Slack team we could use.

**Comment by hasufell** [comment]
> The local functional programming meetup in Sydney called FPSyd as a Slack team we could use.

I don't know how to join that

**Comment by newhoggy** [comment]
I sent an invite link to your posteo.de email address as listed in Github.
