### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by hasufell** [haskell-works/cabal-cache#72]
No matter on what machine I try it, it always throws this:
```
cabal-cache: ~/.cabal/store/ghc-8.6.5/lib: getDirectoryContents:openDirStream: does not exist (No such file or directory)
```

This directory does not exist anywhere. I don't see why it should.

**Comment by AlexeyRaga** [comment]
@hasufell Could you please provide a version of `cabal-cache` and an OS you are running?

When you say that `~/.cabal/store/ghc-8.6.5` shouldn't exist, why so? Do you relocate cabal store?

**Comment by hasufell** [comment]
Latest version, OS Ubuntu. Also, I did not say that `~/.cabal/store/ghc-8.6.5` does not exist. `~/.cabal/store/ghc-8.6.5/lib` does not exist, so it seems the code has wrong assumptions.

**Comment by hasufell** [comment]
Any news?
