### ISSUE TITLE
ghc-pkg invocation doesn't honour current compiler

### ISSUE THREAD

**Issue by hasufell** [haskell-works/cabal-cache#94]
If you have two GHC versions installed:

* 8.6.5
* 8.8.1

And 8.8.1 is the current one (`ghc` symlink), but the project uses 8.6.5, then cabal-cache will:

1. still sync the correct 8.6.5 packages, because it uses the cabal plan
2. somehow break `~/.cabal/store/ghc-8.6.5/package.db/package.cache`

A subsequent build will then throw:

```
cabal: ghc-pkg dump failed: dieVerbatim: user error (cabal:
'/home/curry/.ghcup/bin/ghc-pkg-8.6.5' exited with an error:
ghc-pkg: /home/curry/.cabal/store/ghc-8.6.5/package.db/package.cache:
GHC.PackageDb.readPackageDb: inappropriate type (not enough bytes)
)
```

The output of cabal-cache also clearly shows:

```
GHC package manager version 8.8.1
```

although that is not the project compiler version.

Edit: probably something somewhere here https://github.com/haskell-works/cabal-cache/blob/master/src/HaskellWorks/CabalCache/GhcPkg.hs#L8

Edit2: should probably use `pjCompilerId` from https://hackage.haskell.org/package/cabal-plan-0.6.2.0/docs/Cabal-Plan.html ...another way would be to run `cabal new-exec ghc-pkg`, which does the correct thing too. I'm not sure how feasible that is

**Comment by newhoggy** [comment]
Thanks for the ticket.

`cabal-cache` is very much driven by `dist-newstyle/cache/plan.json`.

The correct thing to do would be to extract the `ghc` version from this file and invoke the correct version of `ghc-pkg`, which in your example would be `ghc-pkg-8.6.5`.

Unfortunately this means `cabal-cache` (when fixed) will ignore what your current `ghc` version i.e. `ghc-8.8.1`.

Is this an acceptable fix for you?

**Comment by newhoggy** [comment]
#97 should prevent the corruption.

**Comment by hasufell** [comment]
seems to work now
